export default function NarrativeCard({ narrative }) {
  const sections = parseNarrative(narrative)

  return (
    <div className="card p-5 h-full">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-sm font-semibold text-ink-900">Underwriter Narrative</h3>
          <p className="text-[11px] text-ink-400">Generated by Claude</p>
        </div>
      </div>

      <div className="text-sm text-ink-700 leading-relaxed space-y-4">
        {sections.map((section, i) => (
          <div key={i}>
            {section.heading && (
              <p className="text-xs font-semibold text-ink-900 uppercase tracking-wide mb-1.5">{section.heading}</p>
            )}
            <p dangerouslySetInnerHTML={{ __html: formatBody(section.body) }} />
          </div>
        ))}
      </div>
    </div>
  )
}

function parseNarrative(markdown) {
  const lines = markdown.split('\n')
  const sections = []
  let current = null

  for (const line of lines) {
    const headingMatch = line.match(/^##\s+(.+)/)
    if (headingMatch) {
      if (current) sections.push(current)
      current = { heading: headingMatch[1], body: '' }
    } else if (current) {
      current.body += (current.body ? '\n' : '') + line
    }
  }
  if (current) sections.push(current)
  return sections
}

function formatBody(text) {
  return text
    .trim()
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-ink-900">$1</strong>')
    .replace(/- \*\*(.+?)\*\*:/g, '&bull; <strong class="text-ink-900">$1</strong>:')
    .replace(/^- (.+)/gm, '&bull; $1')
    .replace(/\n/g, '<br/>')
}
