export default function NarrativeCard({ narrative }) {
  const sections = parseNarrative(narrative)

  return (
    <div className="card p-5 h-full flex flex-col">
      <div className="flex items-center justify-between mb-4 shrink-0">
        <div>
          <h3 className="text-sm font-semibold text-ink-900">Underwriter Narrative</h3>
          <p className="text-[11px] text-ink-400">Generated by Claude</p>
        </div>
      </div>

      <div className="text-sm text-ink-700 leading-relaxed space-y-4 overflow-y-auto max-h-[500px] pr-1">
        {sections.map((section, i) => (
          <div key={i}>
            {section.heading && (
              <p className="text-xs font-semibold text-ink-900 uppercase tracking-wide mb-1.5">{section.heading}</p>
            )}
            <p dangerouslySetInnerHTML={{ __html: formatBody(section.body) }} />
          </div>
        ))}
      </div>
    </div>
  )
}

function parseNarrative(markdown) {
  if (!markdown) return [{ heading: null, body: 'No narrative generated.' }]

  const lines = markdown.split('\n')
  const sections = []
  let current = null
  let preamble = ''

  for (const line of lines) {
    const headingMatch = line.match(/^##\s+(.+)/)
    if (headingMatch) {
      if (current) sections.push(current)
      current = { heading: headingMatch[1], body: '' }
    } else if (current) {
      current.body += (current.body ? '\n' : '') + line
    } else {
      preamble += (preamble ? '\n' : '') + line
    }
  }
  if (current) sections.push(current)

  // If no ## headings were found, treat the whole text as one section
  if (sections.length === 0 && preamble.trim()) {
    sections.push({ heading: null, body: preamble })
  } else if (preamble.trim() && sections.length > 0) {
    sections.unshift({ heading: null, body: preamble })
  }

  return sections
}

function formatBody(text) {
  return text
    .trim()
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-ink-900">$1</strong>')
    .replace(/- \*\*(.+?)\*\*:/g, '&bull; <strong class="text-ink-900">$1</strong>:')
    .replace(/^- (.+)/gm, '&bull; $1')
    .replace(/\n/g, '<br/>')
}
